Added deployment for production

diff --git a/server/Dockerfile.local b/server/Dockerfile.local
--- a/server/Dockerfile.local
+++ b/server/Dockerfile.local
@@ -11,10 +11,11 @@ COPY --chown=node:node package*.json ./
 COPY --chown=node:node tsconfig*.json ./
 
 RUN npm install
-RUN npx prisma generate --schema=./prisma/schema.prisma || (echo "Prisma generate failed" && exit 1)
 
 # Bundle app source
 COPY --chown=node:node . .
+
+RUN npx prisma generate --schema=./prisma/schema.prisma || (echo "Prisma generate failed" && exit 1)
 
 # Use the node user from the image (instead of the root user)
 USER node
