Added E2E tests using playwright (#20)

diff --git a/server/Dockerfile b/server/Dockerfile
--- a/server/Dockerfile
+++ b/server/Dockerfile
@@ -1,23 +1,21 @@
+
 # Use the official Node.js image as the base image
 FROM node:lts-alpine3.21
 
-# Set the working directory inside the container
+# Create app directory
 WORKDIR /usr/src/app
 
-# Copy package.json and package-lock.json to the working directory
-COPY package*.json ./
-
-# Install the application dependencies
+COPY --chown=node:node . .
 RUN npm install
 
-# Copy the rest of the application files
-COPY . .
+RUN npx prisma generate --schema=./prisma/schema.prisma || (echo "Prisma generate failed" && exit 1)
+RUN npm run build && [ -f dist/main.js ] || (echo "Build failed: dist/main.js not found" && exit 1)
 
-# Build the NestJS application
 RUN npm run build
 
-# Expose the application port
-EXPOSE 3001
+# Use the node user from the image (instead of the root user)
+USER node
 
-# Command to run the application
-CMD ["node", "dist/main"]
+EXPOSE 3000
+
+CMD ["npm", "run", "start:prod"]      
