Added E2E tests using playwright

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -15,6 +15,7 @@ jobs:
       PGADMIN_DEFAULT_PASSWORD: ${{ vars.PGADMIN_DEFAULT_PASSWORD }}
 
       SERVER_URL: ${{ vars.SERVER_URL }}
+      DATABASE_URL: ${{ vars.DATABASE_URL }}
 
       PLAYWRIGHT_BASE_URL: ${{ vars.PLAYWRIGHT_BASE_URL }}
       PLAYWRIGHT_USER_USERNAME: ${{ vars.PLAYWRIGHT_USER_USERNAME }}
@@ -30,39 +31,46 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v4
 
-      # - name: Install Docker Compose
-      #   run: |
-      #     sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
-      #     sudo chmod +x /usr/local/bin/docker-compose
-      #     docker-compose --version
-
       - name: Start Docker Compose services
         run: |
           make run-build
         working-directory: .
 
-      - name: Check DNS
+      - name: Sleep
         run: |
-          until docker exec client ping -c 1 -W 1 server >/dev/null 2>&1; do
-            echo "Waiting for server to respond..."
-            sleep 1
-          done
-          echo "Server is reachable!"
+          sleep 60s
 
-      # - name: Run e2e tests
-      #   working-directory: ./testing/e2e
-      #   run: |
-      #     npm ci
-      #     npx playwright install
-      #     npx playwright install-deps
-      #     npx playwright test
+      - name: Check Server Port
+        run: |
+          docker exec server which netstat || echo "netstat not found"
+          docker exec server netstat -tuln | grep 3000 || echo "netstat failed with exit code $?"
+          docker exec server ps -ef || echo "ps failed with exit code $?"
+          docker exec server ss -tuln | grep ':3000' || echo "ss failed with exit code $?"
+          docker inspect server --format='{{.State.Status}}'
 
-      # - uses: actions/upload-artifact@v4
-      #   if: ${{ !cancelled() }}
-      #   with:
-      #     name: playwright-report
-      #     path: ./testing/e2e/playwright-report/
-      #     retention-days: 30
+      - name: Server Logs
+        run: |
+          docker compose logs server
+
+      - name: Verify server
+        run: |
+          docker exec server env || echo "env failed with exit code $?"
+          docker inspect server --format='{{.State.Status}} {{.State.ExitCode}}'
+
+      - name: Run e2e tests
+        working-directory: ./testing/e2e
+        run: |
+          npm ci
+          npx playwright install
+          npx playwright install-deps
+          npx playwright test
+
+      - uses: actions/upload-artifact@v4
+        if: ${{ !cancelled() }}
+        with:
+          name: playwright-report
+          path: ./testing/e2e/playwright-report/
+          retention-days: 30
 
       # - name: Check Docker Compose Logs
       #   if: always() # Run even if previous steps fail
