Added E2E tests using playwright

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -45,18 +45,19 @@ jobs:
       - name: Health Check Endpoint
         run: |
           # Wait for the service to be ready (adjust sleep time as needed)
-          sleep 10
+          sleep 30
 
-          # Curl the health check endpoint and capture the HTTP status code
-          HTTP_STATUS=$(curl --silent --fail -o /dev/null --max-time 5 -w "%{http_code}" http://172.18.0.1:3000/health)
-
-          # Check if the status code is 200
-          if [[ "$HTTP_STATUS" == "200" ]]; then
-            echo "Health check passed!"
-          else
-            echo "Health check failed: HTTP status $HTTP_STATUS"
-            exit 1
-          fi
+          for i in {1..5}; do
+            HTTP_STATUS=$(curl --silent --fail -o /dev/null --max-time 5 -w "%{http_code}" http://localhost:8080/health 2> /dev/null && echo "success" || echo "failed")
+            if [[ "$HTTP_STATUS" == "200" ]]; then
+              echo "Health check passed!"
+              exit 0
+            fi
+            echo "Attempt $i failed, retrying..."
+            sleep 5
+          done
+          echo "Health check failed after retries: HTTP status $HTTP_STATUS"
+          exit 1
       - name: Run e2e tests
         working-directory: ./testing/e2e
         run: |
