Added E2E tests using playwright

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -36,21 +36,23 @@ jobs:
           make run-build
         working-directory: .
 
-      - name: Verify server
-        run: |
-          docker exec server ls -la dist
+      # - name: Verify server
+      #   run: |
+      #     docker run -it server sh
+      #     ls -la /usr/src/app/src
+      #     ls -la /usr/src/app/tsconfig.json
 
       - name: Sleep
         run: |
           sleep 60s
 
-      - name: Check Server Port
-        run: |
-          docker exec server which netstat || echo "netstat not found"
-          docker exec server netstat -tuln | grep 3000 || echo "netstat failed with exit code $?"
-          docker exec server ps -ef || echo "ps failed with exit code $?"
-          docker exec server ss -tuln | grep ':3000' || echo "ss failed with exit code $?"
-          docker inspect server --format='{{.State.Status}}'
+      # - name: Check Server Port
+      #   run: |
+      #     docker exec server which netstat || echo "netstat not found"
+      #     docker exec server netstat -tuln | grep 3000 || echo "netstat failed with exit code $?"
+      #     docker exec server ps -ef || echo "ps failed with exit code $?"
+      #     docker exec server ss -tuln | grep ':3000' || echo "ss failed with exit code $?"
+      #     docker inspect server --format='{{.State.Status}}'
 
       # - name: Server Logs
       #   run: |
diff --git a/server/Dockerfile b/server/Dockerfile
--- a/server/Dockerfile
+++ b/server/Dockerfile
@@ -6,19 +6,27 @@ WORKDIR /usr/src/app
 
 COPY --chown=node:node package.json ./
 COPY --chown=node:node tsconfig*.json ./
+COPY --chown=node:node prisma ./prisma
 
 # Install the application dependencies
 RUN npm install
 
 # Copy the rest of the application files
-COPY . .
+COPY --chown=node:node . .
 
 # Build the NestJS application
-RUN npx prisma generate
-RUN npm run build
+# RUN npx prisma generate
+RUN npx prisma generate || (echo "Prisma generate failed" && exit 1)
+# RUN npm run build
+RUN npm run build && [ -f dist/main.js ] || (echo "Build failed: dist/main.js not found" && exit 1)
+
+# Ensure permissions
+RUN chown -R node:node /usr/src/app/dist
 
 # Expose the application port
 EXPOSE 3000
+
+USER node
 
 # Command to run the application
 CMD ["npm", "run", "start:prod"]
