Added E2E tests using playwright

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -36,40 +36,36 @@ jobs:
           make run-build
         working-directory: .
 
-      - name: Sleep
-        run: |
-          sleep 60s
-
-      # - name: Check Server Port
+      # - name: Sleep
       #   run: |
-      #     docker exec server which netstat || echo "netstat not found"
-      #     docker exec server netstat -tuln | grep 3000 || echo "netstat failed with exit code $?"
-      #     docker exec server ps -ef || echo "ps failed with exit code $?"
-      #     docker exec server ss -tuln | grep ':3000' || echo "ss failed with exit code $?"
-      #     docker inspect server --format='{{.State.Status}}'
+      #     sleep 60s
 
-      # - name: Server Logs
-      #   run: |
-      #     docker compose logs server
-
-      - name: Run e2e tests
-        working-directory: ./testing/e2e
+      - name: Check Server Port
         run: |
-          npm ci
-          npx playwright install
-          npx playwright install-deps
-          npx playwright test
+          docker exec server which netstat || echo "netstat not found"
+          docker exec server netstat -tuln | grep 3000 || echo "netstat failed with exit code $?"
+          docker exec server ps -ef || echo "ps failed with exit code $?"
+          docker exec server ss -tuln | grep ':3000' || echo "ss failed with exit code $?"
+          docker inspect server --format='{{.State.Status}}'
 
-      - uses: actions/upload-artifact@v4
-        if: ${{ !cancelled() }}
-        with:
-          name: playwright-report
-          path: ./testing/e2e/playwright-report/
-          retention-days: 30
+      # - name: Run e2e tests
+      #   working-directory: ./testing/e2e
+      #   run: |
+      #     npm ci
+      #     npx playwright install
+      #     npx playwright install-deps
+      #     npx playwright test
 
-      # - name: Check Docker Compose Logs
-      #   if: always() # Run even if previous steps fail
-      #   run: docker compose logs
+      # - uses: actions/upload-artifact@v4
+      #   if: ${{ !cancelled() }}
+      #   with:
+      #     name: playwright-report
+      #     path: ./testing/e2e/playwright-report/
+      #     retention-days: 30
+
+      - name: Check Docker Compose Logs
+        if: always() # Run even if previous steps fail
+        run: docker compose logs
 
       - name: Stop Docker Compose services
         if: always() # Run even if previous steps fail
