Added E2E tests using playwright

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -38,22 +38,19 @@ jobs:
 
       - name: Inspect Server Container
         run: |
-          docker exec server npx prisma generate
-          docker exec server npm install
-          docker exec server npm run build
-          docker exec server npm run start:prod
+          docker exec server ls -la ./node_modules/.prisma/client
 
       - name: Sleep
         run: |
           sleep 60s
 
-      - name: Check Server Port
-        run: |
-          docker exec server which netstat || echo "netstat not found"
-          docker exec server netstat -tuln | grep 3000 || echo "netstat failed with exit code $?"
-          docker exec server ps -ef || echo "ps failed with exit code $?"
-          docker exec server ss -tuln | grep ':3000' || echo "ss failed with exit code $?"
-          docker inspect server --format='{{.State.Status}}'
+      # - name: Check Server Port
+      #   run: |
+      #     docker exec server which netstat || echo "netstat not found"
+      #     docker exec server netstat -tuln | grep 3000 || echo "netstat failed with exit code $?"
+      #     docker exec server ps -ef || echo "ps failed with exit code $?"
+      #     docker exec server ss -tuln | grep ':3000' || echo "ss failed with exit code $?"
+      #     docker inspect server --format='{{.State.Status}}'
 
       # - name: Server Logs
       #   run: |
@@ -74,9 +71,9 @@ jobs:
           path: ./testing/e2e/playwright-report/
           retention-days: 30
 
-      - name: Check Docker Compose Logs
-        if: always() # Run even if previous steps fail
-        run: docker compose logs
+      # - name: Check Docker Compose Logs
+      #   if: always() # Run even if previous steps fail
+      #   run: docker compose logs
 
       - name: Stop Docker Compose services
         if: always() # Run even if previous steps fail
diff --git a/server/Dockerfile b/server/Dockerfile
--- a/server/Dockerfile
+++ b/server/Dockerfile
@@ -13,10 +13,15 @@ WORKDIR /usr/src/app
 COPY . .
 
 # Install the application dependencies
-# RUN npm install
+RUN npm install
+
+# docker exec server npx prisma generate
+# docker exec server npm install
+# docker exec server npm run build
+# docker exec server npm run start:prod
 
 # Build the NestJS application
-# RUN npx prisma generate || (echo "Prisma generate failed" && exit 1)
+RUN npx prisma generate --schema=./prisma/schema.prisma || (echo "Prisma generate failed" && exit 1)
 # RUN npm run build && [ -f dist/main.js ] || (echo "Build failed: dist/main.js not found" && exit 1)
 
 # Ensure permissions
@@ -28,5 +33,5 @@ EXPOSE 3000
 # USER node
 
 # Command to run the application
-# CMD ["npm", "run", "start:prod"]
-CMD ["tail", "-f", "/dev/null"]
+CMD ["npm", "run", "start:prod"]
+# CMD ["tail", "-f", "/dev/null"]
